lsdklsjdfkjski :wq
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   file1

no changes added to commit (use "git add" and/or "git commit -a")
[root@ip-172-31-31-46 singaporedir]# git config -global user.name "zafar"
error: did you mean `--global` (with two dashes)?
[root@ip-172-31-31-46 singaporedir]# git config --global user.name "zafar"
[root@ip-172-31-31-46 singaporedir]# git config --global user.email "zafar@gmail.com"
[root@ip-172-31-31-46 singaporedir]# git add .
[root@ip-172-31-31-46 singaporedir]# git commit -m
error: switch `m' requires a value
[root@ip-172-31-31-46 singaporedir]# git commit -m
error: switch `m' requires a value
[root@ip-172-31-31-46 singaporedir]# git commit
hint: Waiting for your editor to close the file...

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   file1

no changes added to commit (use "git add" and/or "git commit -a")
[root@ip-172-31-31-46 singaporedir]# git config -global user.name "zafar"
error: did you mean `--global` (with two dashes)?
[root@ip-172-31-31-46 singaporedir]# git config --global user.name "zafar"
[root@ip-172-31-31-46 singaporedir]# git config --global user.email "zafar@gmail.com"
[root@ip-172-31-31-46 singaporedir]# git add .
[root@ip-172-31-31-46 singaporedir]# git commit -m
error: switch `m' requires a value
[root@ip-172-31-31-46 singaporedir]# git commit -m
error: switch `m' requires a value
[root@ip-172-31-31-46 singaporedir]# git commit
hint: Waiting for your editor to close the file...

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   file1

no changes added to commit (use "git add" and/or "git commit -a")
[root@ip-172-31-31-46 singaporedir]# git config -global user.name "zafar"
error: did you mean `--global` (with two dashes)?
[root@ip-172-31-31-46 singaporedir]# git config --global user.name "zafar"
[root@ip-172-31-31-46 singaporedir]# git config --global user.email "zafar@gmail.com"
[root@ip-172-31-31-46 singaporedir]# git add .
[root@ip-172-31-31-46 singaporedir]# git commit -m
error: switch `m' requires a value
[root@ip-172-31-31-46 singaporedir]# git commit -m
error: switch `m' requires a value
[root@ip-172-31-31-46 singaporedir]# git commit
hint: Waiting for your editor to close the file...

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   file1

no changes added to commit (use "git add" and/or "git commit -a")
[root@ip-172-31-31-46 singaporedir]# git config -global user.name "zafar"
error: did you mean `--global` (with two dashes)?
[root@ip-172-31-31-46 singaporedir]# git config --global user.name "zafar"
[root@ip-172-31-31-46 singaporedir]# git config --global user.email "zafar@gmail.com"
[root@ip-172-31-31-46 singaporedir]# git add .
[root@ip-172-31-31-46 singaporedir]# git commit -m
error: switch `m' requires a value
[root@ip-172-31-31-46 singaporedir]# git commit -m
error: switch `m' requires a value
[root@ip-172-31-31-46 singaporedir]# git commit
hint: Waiting for your editor to close the file...

jshdjsdhfjkdhfjkdhfu